# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525d100bc73ae6ceb8cbdc2e6abf34d8faa487beb585a1df8c5fe655278f0c52895a461af97af2d535650a73e82fe944c2c35ea0d612aad363d141cbf718ddef

test:
  secret_key_base: 14fd15cac7b8846c39ea44f4f487ab72c7fe3e485366626ce1f3a216c907a0bc3660aea40645cda51e27cf7982a24865dc1c5b7e12fbd37efea869ff1fd5f2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
